title: Jekyll Actions Guide
description: "How to setup Github Pages + Actions for use with Jekyll 4"

url: "https://lncslncs.github.io"
baseurl: "/site_gha"

github_username: lncslncs

markdown: kramdown
theme: minima
plugins:
  - jekyll-timeago
